## packages to install and manage R packages
options(BioC_mirror="https://mirrors.tuna.tsinghua.edu.cn/bioconductor")
options(repos=structure(c(CRAN="https://mirrors.tuna.tsinghua.edu.cn/CRAN/")))  
# install.packages("pacman")
# install.packages("BiocManager")
# install.packages("devtools")



pacman::p_load('Rcpp')

pacman::p_load("gplots")
pacman::p_load("ggplot2")
pacman::p_load("scatterplot3d")
pacman::p_load("Hmisc")
pacman::p_load("stringr")
pacman::p_load("rgl")
pacman::p_load("RColorBrewer")
pacman::p_load("survival")
pacman::p_load("ggpubr")
pacman::p_load("ggthemes")
pacman::p_load("stringr")
pacman::p_load("Rtsne")
pacman::p_load("pheatmap")
pacman::p_load("WGCNA")
pacman::p_load("e1071")
pacman::p_load("limma")
pacman::p_load("org.Hs.eg.db")
pacman::p_load("clusterProfiler")
pacman::p_load("sva")
pacman::p_load("pamr")
pacman::p_load("impute")
pacman::p_load("preprocessCore")
pacman::p_load("GO.db")
pacman::p_load("ggsci")

pacman::p_load("cowplot")
pacman::p_load("openxlsx")
pacman::p_load("enrichplot")
pacman::p_load("TCGAbiolinks")
pacman::p_load("SummarizedExperiment")
pacman::p_load("dplyr")
pacman::p_load("DT")
pacman::p_load("parallel")
pacman::p_load("ggcorrplot")
pacman::p_load("ggplotify")
pacman::p_load("glmnet")
pacman::p_load("pROC")
pacman::p_load("tableone")
pacman::p_load("class")
pacman::p_load("randomForest")
pacman::p_load("foreign")
pacman::p_load("rms")
pacman::p_load("survival")
pacman::p_load("rpart")
pacman::p_load("treeheatr")
pacman::p_load("rmda")
pacman::p_load("PredictABEL")
pacman::p_load("MASS")
pacman::p_load("caret")
pacman::p_load("forestplot")
pacman::p_load("Formula")
pacman::p_load("survminer")
pacman::p_load("DESeq2")
pacman::p_load("wesanderson")


pacman::p_load("RSpectra")
pacman::p_load("umap")
pacman::p_load("maftools")




# Check if the packages are successfully installed.
library("gplots")
library("ggplot2")
library("scatterplot3d")
library("Hmisc")
library("stringr")
library("rgl")
library("RColorBrewer")
library("survival")
library("ggpubr")
library("ggthemes")
library("stringr")
library("Rtsne")
library("pheatmap")
library("WGCNA")
library("e1071")
library("limma")
library("org.Hs.eg.db")
library("clusterProfiler")
library("sva")
library("pamr")
library("impute")
library("preprocessCore")
library("GO.db")
library("ggsci")
library("umap")
library("cowplot")
library("openxlsx")
library("enrichplot")
library("TCGAbiolinks")
library("SummarizedExperiment")
library("dplyr")
library("DT")
library("parallel")
library("ggcorrplot")
library("ggplotify")
library("glmnet")
library("pROC")
library("tableone")
library("class")
library("randomForest")
library("foreign")
library("rms")
library("survival")
library("rpart")
library("treeheatr")
library("rmda")
library("PredictABEL")
library("MASS")
library("caret")
library("forestplot")
library("Formula")
library("survminer")
library("DESeq2")
library("wesanderson")
library(maftools)


# guozi install -----------------------------------------------------------




options("repos"=c(CRAN="https://mirrors.tuna.tsinghua.edu.cn/CRAN/"))
options(BioC_mirror="https://mirrors.tuna.tsinghua.edu.cn/bioconductor")

if(!requireNamespace("tidyr",quietly = TRUE)) install.packages("tidyr",update = F,ask = F)
if(!requireNamespace("dplyr",quietly = TRUE)) install.packages("dplyr",update = F,ask = F)
if(!requireNamespace("ggplot2",quietly = TRUE)) install.packages("ggplot2",update = F,ask = F)
if(!requireNamespace("data.table",quietly = TRUE)) install.packages("data.table",update = F,ask = F)
if(!requireNamespace("ggrepel",quietly = TRUE)) install.packages("ggrepel",update = F,ask = F)
if(!requireNamespace("pheatmap",quietly = TRUE)) install.packages("pheatmap",update = F,ask = F)
if(!requireNamespace("ggfortify",quietly = TRUE)) install.packages("ggfortify",update = F,ask = F)
if(!requireNamespace("ggpubr",quietly = TRUE)) install.packages("ggpubr",update = F,ask = F)
if(!requireNamespace("ggsignif",quietly = TRUE)) install.packages("ggsignif",update = F,ask = F)
if(!requireNamespace("tibble",quietly = TRUE)) install.packages("tibble",update = F,ask = F)
if(!requireNamespace("cowplot",quietly = TRUE)) install.packages("cowplot",update = F,ask = F)
if(!requireNamespace("BiocManager",quietly = TRUE)) install.packages("BiocManager",update = F,ask = F)

if(!requireNamespace("limma",quietly = TRUE)) BiocManager::install("limma",update = F,ask = F)
if(!requireNamespace("Biobase",quietly = TRUE)) BiocManager::install("Biobase",update = F,ask = F)
if(!requireNamespace("NMF",quietly = TRUE)) install.packages("NMF",update = F,ask = F)
if(!requireNamespace("IRanges",quietly = TRUE)) BiocManager::install("IRanges",update = F,ask = F)
if(!requireNamespace("GenomeInfoDbData",quietly = TRUE)) BiocManager::install("GenomeInfoDbData",update = F,ask = F)
if(!requireNamespace("DO.db",quietly = TRUE)) BiocManager::install("DO.db",update = F,ask = F)
if(!requireNamespace("GO.db",quietly = TRUE)) BiocManager::install("GO.db",update = F,ask = F)
if(!requireNamespace("fgsea",quietly = TRUE)) BiocManager::install("fgsea",update = F,ask = F)
if(!requireNamespace("gridGraphics",quietly = TRUE)) BiocManager::install("gridGraphics",update = F,ask = F)
if(!requireNamespace("clusterProfiler",quietly = TRUE)) BiocManager::install("clusterProfiler",update = F,ask = F)
if(!requireNamespace("GEOquery",quietly = TRUE)) BiocManager::install("GEOquery",update = F,ask = F)
if(!requireNamespace("hugene10sttranscriptcluster.db",quietly = TRUE)) BiocManager::install("hugene10sttranscriptcluster.db",update = F,ask = F)
if(!requireNamespace("DOSE",quietly = TRUE)) BiocManager::install("DOSE",update = F,ask = F)
if(!requireNamespace("GSEABase",quietly = TRUE)) BiocManager::install("GSEABase",update = F,ask = F)
if(!requireNamespace("enrichplot",quietly = TRUE)) BiocManager::install("enrichplot",update = F,ask = F)
if(!requireNamespace("bladderbatch",quietly = TRUE)) BiocManager::install("bladderbatch",update = F,ask = F)
if(!requireNamespace("sva",quietly = TRUE)) BiocManager::install("sva",update = F,ask = F)
if(!requireNamespace("DESeq2",quietly = TRUE)) BiocManager::install("DESeq2",update = F,ask = F)
if(!requireNamespace("edgeR",quietly = TRUE)) BiocManager::install("edgeR",update = F,ask = F)
if(!requireNamespace("pathview",quietly = TRUE)) BiocManager::install("pathview",update = F,ask = F)
if(!requireNamespace("vsn",quietly = TRUE)) BiocManager::install("vsn",update = F,ask = F)
if(!requireNamespace("GSVA",quietly = TRUE)) BiocManager::install("GSVA",update = F,ask = F)


# Newest----------------------------------------------------------------



if(!requireNamespace("xfun",quietly = TRUE)) BiocManager::install("xfun",update = T,ask = T)
BiocManager::install("xfun",update = T,ask = T)
library("survminer")


remove.packages("xfun")
require(devtools)
#install_version("xfun", version = "0.27",repos = "http://cran.us.r-project.org")

#https://mirrors.tuna.tsinghua.edu.cn/CRAN/

# install_version("xfun", version = "0.27",repos = "https://mirrors.tuna.tsinghua.edu.cn/CRAN/")
install_version("xfun", version = "0.29",repos = "https://mirrors.tuna.tsinghua.edu.cn/CRAN/")
